name: bloc_studies
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.21.1

flutter:
  uses-material-design: true
